---

- name: Run Jugglers
  hosts: localhost
  connection: local
  become: true
  vars:
    jugglers_number: "{{ jugglers_number }}"
  tasks:
    - name: Delete the arena
      file:
        state: absent
        path: "{{ playbook_dir }}/arena"

    - name: Re-create the arena
      file:
        state: directory
        path: "{{ playbook_dir }}/arena"

    - name: Delete all already existing containers
      ansible.builtin.shell: |
        docker ps -a | awk '{ print $1,$2 }' | grep container_{{ item }} | awk '{print $1 }' | xargs -I {} docker rm -f {}
      with_sequence:
        - "1-{{ jugglers_number }}"

    - name: Copy container {{ jugglers_number }} time
      copy:
        src: "{{ playbook_dir }}/container/"
        dest: "{{ playbook_dir }}/arena/container_{{ item }}"
      with_sequence:
        - "1-{{ jugglers_number }}"

    # Current:
    - name: update current container total_containers number
      ansible.builtin.lineinfile:
        path: "{{ playbook_dir }}/arena/container_{{ item }}/config.yaml"
        search_string: "total_containers:"
        line: "total_containers: {{ jugglers_number }}"
      with_sequence:
        - "1-{{ jugglers_number }}"

    - name: update current container url
      ansible.builtin.lineinfile:
        path: "{{ playbook_dir }}/arena/container_{{ item }}/config.yaml"
        search_string: "current_url:"
        line: "    current_url: container_{{ item }}"
      with_sequence:
        - "1-{{ jugglers_number }}"

    - name: update current container id
      ansible.builtin.lineinfile:
        path: "{{ playbook_dir }}/arena/container_{{ item }}/config.yaml"
        search_string: "current_id:"
        line: "    current_id: {{ item }}"
      with_sequence:
        - "1-{{ jugglers_number }}"

    # Next
    - name: update next container url
      ansible.builtin.lineinfile:
        path: "{{ playbook_dir }}/arena/container_{{ item }}/config.yaml"
        search_string: "next_url:"
        line: "    next_url: container_{{ (item|int + 1) | string  }}"
      with_sequence:
        - "1-{{ jugglers_number }}"

    # Last
    - name: update last container url
      ansible.builtin.lineinfile:
        path: "{{ playbook_dir }}/arena/container_{{ jugglers_number }}/config.yaml"
        search_string: "next_url:"
        line: "    next_url: container_1"

    # Put ball in 1 container
    - name: Put ball in 1 container
      copy:
        src: "{{ playbook_dir }}/ball.txt"
        dest: "{{ playbook_dir }}/arena/container_1/volume/ball.txt"

    - name: Get info on juggle_network
      docker_network_info:
        name: juggle_network
      register: network_exist

    - name: Create network if it doesn't exist
      ansible.builtin.shell: |
        docker network create juggle_network
      args:
        chdir: "{{ playbook_dir }}/arena/container_{{ jugglers_number }}"
      when: not network_exist

    - name: Build containers
      ansible.builtin.shell: |
        docker build -t container_{{ item }} .
      args:
        chdir: "{{ playbook_dir }}/arena/container_{{ item }}"
      with_sequence:
        - "1-{{ jugglers_number }}"

    - name: Run containers
      ansible.builtin.shell: |
        docker run --name container_{{ item }} --net="juggle_network" -p 500{{ item }}:5000 -d container_{{ item }}
      args:
        chdir: "{{ playbook_dir }}/arena/container_{{ jugglers_number }}"
      with_sequence:
        - "1-{{ jugglers_number }}"




